-- =============================================================================
-- 026 — Backfill exam_rules.descricao com a Descrição oficial das fichas MBEDV.
--
-- Gerado de configs/references/mbedv_fichas.json (campo descricao) via
-- seed_mbedv.regras_canonicas(). A prod foi populada por migration SQL (o JSON
-- não está na imagem), então o backfill vai como dados versionados, não reseed.
-- Idempotente: re-rodar grava o mesmo valor. Chave: codigo_val.
-- =============================================================================

UPDATE exam_rules SET descricao = 'No exame de direção veicular, a atenção e cuidados indispensáveis a segurança são caracterizados por foco e atenção durante todo o percurso.' WHERE codigo_val = 'VAL-CTB-169';
UPDATE exam_rules SET descricao = 'Ocorre quando o condutor age com a intenção deliberada de intimidar, assustar ou forçar a travessia do pedestre, durante a realização do percurso.' WHERE codigo_val = 'VAL-CTB-170';
UPDATE exam_rules SET descricao = 'Ocorre quando o condutor utiliza o veículo para intimidar, bloquear ou colocar em risco outros motoristas, durante o percurso.' WHERE codigo_val = 'VAL-CTB-170';
UPDATE exam_rules SET descricao = 'O ato infracional consiste em lançar, propositalmente ou por negligência grave, água ou quaisquer detritos (lama, cascalho, lixo) que se encontrem na via, atingindo um pedestre que esteja na calçada ou atravessando, ou outro veículo, durante o percurso.' WHERE codigo_val = 'VAL-CTB-171';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, a pontuação ocorre quando o condutor utiliza o seu veículo para projetar água, lama ou detritos que estão na pista de rolamento contra outro veículo, sujando-o e, potencialmente, colocando-o em risco.' WHERE codigo_val = 'VAL-CTB-171';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, é o ato de arremessar qualquer objeto ou substância para fora do veículo, estando ele em movimento ou parado, durante todo o percurso.' WHERE codigo_val = 'VAL-CTB-172';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, é o ato de abandonar na via e refere-se a deixar ou largar objetos ou substâncias na superfície da via (pista de rolamento, acostamento, calçada etc. É uma conduta passiva, mas intencional, que cria um obstáculo ou perigo para outros usuários, durante todo o percurso.' WHERE codigo_val = 'VAL-CTB-172';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, o cerne da infração é a intencionalidade do condutor em demonstrar ou exibir destreza ou audácia, realizando manobras que, por sua natureza, colocam em risco a segurança de si próprio e dos demais usuários da via, durante o percurso.' WHERE codigo_val = 'VAL-CTB-175';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, a infração varia em gravidade conforme o potencial de risco e obstrução que o estacionamento indevido representa para o tráfego e a segurança. O estacionamento é definido como a imobilização do veículo por tempo superior ao necessário para embarque ou desembarque de passageiros (que seria uma parada), durante o percurso.' WHERE codigo_val = 'VAL-CTB-181-I, II, III, IV, V, VI, VII, VIII, IX, X, XI, XII, XIII, XIV, XV, XVI, XVII, XVIII, XIX, XX';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, configura-se quando o candidato para o veículo em cima da faixa de pedestres quando da mudança do sinal luminoso. Trata-se especificamente de um erro de conduta que compromete a segurança e o direito de passagem do pedestre nos cruzamentos controlados por semáforo, durante o percurso.' WHERE codigo_val = 'VAL-CTB-183';
UPDATE exam_rules SET descricao = 'No exame de direção veicular a falta deverá ser anotada quando o candidato conduzir o veículo em local exclusivo a outra categoria ou espécie de veículo.' WHERE codigo_val = 'VAL-CTB-184-I';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, a falta deverá ser anotada quando o candidato conduzir em faixa da esquerda em local exclusivo a outro tipo de veículo.' WHERE codigo_val = 'VAL-CTB-184-II';
UPDATE exam_rules SET descricao = 'No exame de direção veicular a falta deverá ser anotada quando o candidato conduzir o veículo em local exclusivo ao transporte público de passageiros.' WHERE codigo_val = 'VAL-CTB-184-III';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, a falta deverá ser anotada quando o candidato tiver percurso determinado a cumprir e deixar de conduzir em faixa destinada a circulação.' WHERE codigo_val = 'VAL-CTB-185-I';
UPDATE exam_rules SET descricao = 'No exame de direção veicular a falta deverá ser anotada quando o candidato tiver percurso determinado a cumprir e deixar de conduzir em faixa destinada a circulação' WHERE codigo_val = 'VAL-CTB-185-II';
UPDATE exam_rules SET descricao = 'A falta deverá ser anotada quando o candidato conduzir em contramão de direção e avançar a via em sentido contrário, em local não autorizado, ou em tempo superior ao necessário para realizar a manobra ou ainda sem respeitar a preferência do veículo que transita em sentido oposto.' WHERE codigo_val = 'VAL-CTB-186-I';
UPDATE exam_rules SET descricao = 'A falta deverá ser anotada quando o candidato conduzir em sentido oposto ao da via com sentido único de direção' WHERE codigo_val = 'VAL-CTB-186-II';
UPDATE exam_rules SET descricao = 'A falta deverá ser anotada quando o candidato transitar via com regulamentação específica quanto a circulação ou horário de circulação.' WHERE codigo_val = 'VAL-CTB-187';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, quando transitar ao lado de outro veículo, interrompendo ou perturbando o trânsito.' WHERE codigo_val = 'VAL-CTB-188';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, deixar de dar passagem aos veículos precedidos de batedores, de socorro de incêndio e salvamento, de polícia, de operação e fiscalização de trânsito e às ambulâncias, quando em serviço de urgência e devidamente identificados por dispositivos regulamentados de alarme sonoro e iluminação intermitente.' WHERE codigo_val = 'VAL-CTB-189';
UPDATE exam_rules SET descricao = 'Seguir veículo em serviço de urgência, estando este com prioridade de passagem devidamente identificada por dispositivos regulamentares de alarme sonoro e iluminação intermitente.' WHERE codigo_val = 'VAL-CTB-190';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, forçar passagem entre veículos que, transitando em sentidos opostos, estejam na iminência de passar um pelo outro ao realizar operação de ultrapassagem.' WHERE codigo_val = 'VAL-CTB-191';
UPDATE exam_rules SET descricao = 'Deixar o candidato na condução do veículo automotor, de guardar distância de segurança lateral e frontal entre o seu veículo e os demais, bem como em relação ao bordo da pista, considerando-se, no momento, a velocidade, as condições climáticas do local da circulação e do veículo.' WHERE codigo_val = 'VAL-CTB-192';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, transitar com o veículo em calçadas, passeios, passarelas, ciclovias, ciclofaixas, ilhas, refúgios, ajardinamentos, canteiros centrais e divisores de pista de rolamento, acostamentos, marcas de canalização, gramados e jardins públicos.' WHERE codigo_val = 'VAL-CTB-193';
UPDATE exam_rules SET descricao = 'Transitar em marcha à ré, salvo na distância necessária a pequenas manobras e de forma a não causar riscos à segurança.' WHERE codigo_val = 'VAL-CTB-194';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, desobedecer às ordens emanadas da autoridade competente de trânsito ou de seus agentes.' WHERE codigo_val = 'VAL-CTB-195';
UPDATE exam_rules SET descricao = 'Deixar de indicar com antecedência, mediante gesto regulamentar de braço ou luz indicadora de direção do veículo, o início da marcha, a realização da manobra de parar o veículo, a mudança de direção ou de faixa de circulação.' WHERE codigo_val = 'VAL-CTB-196';
UPDATE exam_rules SET descricao = 'Esta infração será verificada quando o candidato deixar de deslocar, com antecedência, o veículo para a faixa mais à esquerda ou mais à direita, dentro da respectiva mão de direção, quando for manobrar para um desses lados.' WHERE codigo_val = 'VAL-CTB-197';
UPDATE exam_rules SET descricao = 'Deixar de dar passagem pela esquerda, quando solicitado.' WHERE codigo_val = 'VAL-CTB-198';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, ultrapassar pela direita, salvo quando o veículo da frente estiver colocado na faixa apropriada e der sinal de que vai entrar à esquerda.' WHERE codigo_val = 'VAL-CTB-199';
UPDATE exam_rules SET descricao = 'Ultrapassar pela direita veículo de transporte coletivo ou escolar parado para embarque ou desembarque de passageiros.' WHERE codigo_val = 'VAL-CTB-200';
UPDATE exam_rules SET descricao = 'Deixar de guardar a distância lateral de 1,5 m ao passar ou ultrapassar bicicleta.' WHERE codigo_val = 'VAL-CTB-201';
UPDATE exam_rules SET descricao = 'Ultrapassar pelo acostamento.' WHERE codigo_val = 'VAL-CTB-202-I';
UPDATE exam_rules SET descricao = 'Durante o exame de direção, é proibido ultrapassar outro veículo em cruzamentos, interseções ou passagens de nível (como trilhos de trem). Essa manobra é extremamente perigosa, pois nesses locais há alto risco de colisão lateral ou frontal, além de interferência com outros fluxos de tráfego.' WHERE codigo_val = 'VAL-CTB-202-II';
UPDATE exam_rules SET descricao = 'Durante o exame de direção, o candidato não deve realizar ultrapassagem pela contramão em locais onde a visibilidade é insuficiente, como em curvas, aclives ou declives. Esses pontos apresentam risco elevado de colisões frontais, já que o condutor não consegue visualizar com antecedência o fluxo de veículos no sentido oposto.' WHERE codigo_val = 'VAL-CTB-203-I';
UPDATE exam_rules SET descricao = 'Durante o exame de direção, o candidato não deve ultrapassar pela contramão outro veículo que esteja próximo ou sobre faixas de pedestres. Essa conduta é extremamente perigosa, pois compromete a segurança dos pedestres e demonstra falta de direção defensiva e atenção à sinalização horizontal.' WHERE codigo_val = 'VAL-CTB-203-II';
UPDATE exam_rules SET descricao = 'Durante o exame de direção veicular, o candidato não deve realizar ultrapassagem pela contramão em locais como pontes, viadutos ou túneis, pois são trechos de pista estreita e de fluxo confinado, sem áreas de escape e com baixa possibilidade de manobra evasiva. Essas condições tornam qualquer ultrapassagem extremamente perigosa e contrária às normas de circulação.' WHERE codigo_val = 'VAL-CTB-203-III';
UPDATE exam_rules SET descricao = 'Durante o exame de direção, o candidato não deve ultrapassar pela contramão veículos parados em fila em razão de semáforo, porteira, cancela, cruzamento ou qualquer outro bloqueio momentâneo.' WHERE codigo_val = 'VAL-CTB-203-IV';
UPDATE exam_rules SET descricao = 'Durante o exame de direção, o candidato não deve realizar ultrapassagem pela contramão em trechos da via onde exista linha amarela contínua (simples ou dupla), que indica proibição de ultrapassar. Essas linhas delimitam áreas de risco e visibilidade reduzida, e sua desobediência representa falta grave de observância da sinalização horizontal e das normas de segurança viária.' WHERE codigo_val = 'VAL-CTB-203-V';
UPDATE exam_rules SET descricao = 'Durante o exame de direção, o candidato deve demonstrar capacidade de avaliar o local e o momento correto para cruzar a pista ou realizar conversão à esquerda. Quando não houver local apropriado para retorno, o condutor deve encostar e parar no acostamento à direita, aguardando o momento seguro para realizar a manobra.' WHERE codigo_val = 'VAL-CTB-204';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, a condução do veículo de maneira segura é obrigatória, durante todo o percurso, para tanto o candidato não deve ultrapassar veículo em movimento que integre cortejo, préstito, desfile e formações militares, salvo com autorização da autoridade de trânsito ou de seus agentes.' WHERE codigo_val = 'VAL-CTB-205';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, esta falta deverá ser anotada quando o candidato executar manobra de retorno em local onde a sinalização vertical ou horizontal proíbe expressamente essa manobra.' WHERE codigo_val = 'VAL-CTB-206-I';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, esta falta deverá ser anotada quando o candidato realizar manobra de retorno em locais que, pela geometria da via ou estrutura, oferecem risco à segurança e à visibilidade, como curvas, trechos elevados, túneis e áreas com baixa percepção de aproximação de outros veículos.' WHERE codigo_val = 'VAL-CTB-206-II';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, esta falta deverá ser anotada quando o candidato utiliza áreas não destinadas ao tráfego de veículos para realizar retorno, comprometendo a segurança e ultrapassando os limites físicos da pista de rolamento.' WHERE codigo_val = 'VAL-CTB-206-III';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, esta falta deverá ser anotada quando o candidato, ao tentar realizar retorno em interseção, ingressa na via transversal posicionando-se no sentido oposto ao correto, colocando em risco a circulação de veículos que trafegam naquela via.' WHERE codigo_val = 'VAL-CTB-206-IV';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, esta falta deverá ser anotada quando o candidato realiza manobra de retorno em local permitido, mas de forma insegura, causando risco, impedindo a fluidez do trânsito, obrigando outros veículos a parar, frear bruscamente ou desviar.' WHERE codigo_val = 'VAL-CTB-206-V';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, esta falta deverá ser anotada quando o candidato realizar conversão à direita ou à esquerda em local onde exista sinalização proibitiva específica, desrespeitando a orientação indicada na via.' WHERE codigo_val = 'VAL-CTB-207';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, esta falta deverá ser anotada quando o candidato deixa de obedecer ao sinal vermelho do semáforo ou à placa de Parada Obrigatória (R-1), colocando em risco a segurança da circulação. Não se caracteriza a falta quando houver sinalização que autorize a livre conversão à direita nos termos do art. 44-A.' WHERE codigo_val = 'VAL-CTB-208';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, esta falta deverá ser anotada quando o candidato ignora, desrespeita ou ultrapassa ponto de bloqueio policial, barreira, fiscalização ou ordem de parada emanada da autoridade de trânsito ou policial.' WHERE codigo_val = 'VAL-CTB-210';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, esta falta deverá ser anotada quando o candidato ultrapassar pela esquerda ou pela direita veículos que aguardam em fila, parados em função de semáforo, cancelas (ferrovia, pedágio), bloqueios ou obstáculos temporários, criando risco ou vantagem indevida na circulação.' WHERE codigo_val = 'VAL-CTB-211';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, esta falta deverá ser anotada quando o candidato deixa de realizar a parada obrigatória antes da passagem de nível com linha férrea, independentemente da presença ou não de barreiras, sinalização eletrônica, placas ou dispositivos de advertência adicionais.' WHERE codigo_val = 'VAL-CTB-212';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, esta falta deverá ser anotada quando o candidato não interrompe totalmente a marcha do veículo diante de um agrupamento de pessoas que impede a continuidade da circulação, independentemente de haver sinalização, agente ou indicação adicional.' WHERE codigo_val = 'VAL-CTB-213-I';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, esta falta deverá ser anotada quando o candidato, ao se deparar com agrupamento organizado de veículos que impede a continuidade da circulação, deixa de interromper completamente a marcha, colocando em risco a segurança e o ordenamento do fluxo.' WHERE codigo_val = 'VAL-CTB-213-II';
UPDATE exam_rules SET descricao = 'A falta deverá ser anotada quando o candidato não respeitar a preferência do pedestre ou veículo não motorizado que esteja aguardando para iniciar a travessia.' WHERE codigo_val = 'VAL-CTB-214-I';
UPDATE exam_rules SET descricao = 'A falta deverá ser anotada quando o candidato movimentar o veículo e o pedestre ou o veículo não motorizado não ter concluído a travessia.' WHERE codigo_val = 'VAL-CTB-214-II';
UPDATE exam_rules SET descricao = 'A falta deverá ser anotada quando o candidato movimentar o veículo não respeitando a preferência de pessoas com deficiência, crianças, idosos e gestantes.' WHERE codigo_val = 'VAL-CTB-214-III';
UPDATE exam_rules SET descricao = 'A falta deverá ser anotada quando o candidato movimentar o veículo não respeitando a passagem ou a travessia de pedestres ou veículos não motorizados mesmo que em locais onde não haja indicação de faixa destinada a travessia ou passagem.' WHERE codigo_val = 'VAL-CTB-214-IV';
UPDATE exam_rules SET descricao = 'A falta deverá ser anotada quando o candidato não der a preferência ao pedestre ou veículo que esteja em via transversal.' WHERE codigo_val = 'VAL-CTB-214-V';
UPDATE exam_rules SET descricao = 'A falta deverá ser anotada quando o candidato não der a preferência ao veículo que já estiver circulando em rotatória, ou quando não respeitar a preferência de passagem ao circular ou entrar em outra via.' WHERE codigo_val = 'VAL-CTB-215-I';
UPDATE exam_rules SET descricao = 'A falta deverá ser anotada quando o candidato não der a preferência em momentos de intersecção ao veículo estiver à direita e desejar mudar de sentido de direção.' WHERE codigo_val = 'VAL-CTB-215-I';
UPDATE exam_rules SET descricao = 'A falta deverá ser anotada quando o candidato não der a preferência onde houver sinalização indicativa.' WHERE codigo_val = 'VAL-CTB-215-II';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, a conduta infracional consiste em entrar ou sair de áreas lindeiras (que margeiam a via) sem cumprir duas exigências fundamentais de segurança e circulação, durante todo o percurso.' WHERE codigo_val = 'VAL-CTB-216';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, a infração ocorre quando o condutor realiza o movimento de entrar ou sair de uma fila de veículos estacionados sem garantir a segurança e a fluidez dos outros usuários da via, durante todo o percurso.' WHERE codigo_val = 'VAL-CTB-217';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, a infração ocorre quando o condutor é flagrado transitando em velocidade superior à máxima regulamentada para a via, mas o excesso não ultrapassa 20% desse limite, durante o percurso.' WHERE codigo_val = 'VAL-CTB-218-I';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, a infração ocorre quando o condutor é flagrado transitando em velocidade superior à máxima regulamentada para a via, sendo 20% até 50% desse limite, durante o percurso.' WHERE codigo_val = 'VAL-CTB-218-II';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, a infração ocorre quando o condutor é flagrado transitando em velocidade superior à máxima regulamentada para a via, em mais de 50% desse limite, durante o percurso.' WHERE codigo_val = 'VAL-CTB-218-III';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, pune o condutor que, sem justificativa válida, trafega de forma muito lenta, tornando-se um obstáculo e um fator de risco para o fluxo normal de veículos, durante o percurso.' WHERE codigo_val = 'VAL-CTB-219';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, deixar de reduzir a velocidade do veículo de forma compatível com a segurança do trânsito nas situações descritas abaixo.' WHERE codigo_val = 'VAL-CTB-220';
UPDATE exam_rules SET descricao = 'Fazer uso do facho de luz alta dos faróis em vias providas de iluminação pública.' WHERE codigo_val = 'VAL-CTB-224';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, o candidato usa a buzina nas situações descritas abaixo.' WHERE codigo_val = 'VAL-CTB-227';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, o uso correto do limpador de para-brisa sob chuva é obrigatório, a fim de garantir a visibilidade do percurso. O limpador de para-brisa deve ser utilizado sob chuva, com velocidade condizente com a intensidade da chuva, durante todo o percurso.' WHERE codigo_val = 'VAL-CTB-230-XIX';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, o veículo deve estar ligado e engrenado nos declives, durante todo o percurso.' WHERE codigo_val = 'VAL-CTB-231-IX';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, o uso do capacete devidamente ajustado à cabeça e vestuário adequado, de acordo com as normas e as especificações aprovadas pelo Contran, são obrigatórios para o candidato.' WHERE codigo_val = 'VAL-CTB-244-I';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, a condução do veículo de maneira segura é obrigatória para o candidato durante todo o percurso. O candidato deve fazer o percurso pré-determinado para o exame de maneira segura e equilibrando-se nas duas rodas do veículo.' WHERE codigo_val = 'VAL-CTB-244-III';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, a condução do veículo de maneira segura é obrigatória para o candidato durante todo o percurso. O candidato deve conduzir o veículo segurando o guidom com as duas mãos, salvo eventualmente para indicação de manobras.' WHERE codigo_val = 'VAL-CTB-244-VII';
UPDATE exam_rules SET descricao = 'No exame de direção veicular, o uso do capacete, devidamente ajustado à cabeça, com a viseira fechada ou óculos de proteção, de acordo com a regulamentação do Contran, é obrigatório para o candidato.' WHERE codigo_val = 'VAL-CTB-244-X';
UPDATE exam_rules SET descricao = 'Durante o exame de direção, o candidato deve demonstrar atenção e responsabilidade no uso do sistema de iluminação do veículo. A luz baixa deve permanecer acesa:
• Durante a noite, para garantir visibilidade adequada;
• De dia, em túneis, sob chuva, neblina ou cerração;
• De dia, em rodovias de pista simples fora dos perímetros urbanos, quando o veículo não possuir luzes de rodagem diurna.
O uso correto da iluminação contribui para a segurança ativa e visibilidade mútua entre condutores e pedestres.' WHERE codigo_val = 'VAL-CTB-250-I';
UPDATE exam_rules SET descricao = 'Durante o exame de direção, o candidato deve utilizar corretamente o sistema de iluminação e sinalização do veículo. O pisca-alerta é destinado exclusivamente a situações de imobilização ou emergência, e seu uso indevido pode confundir outros condutores e comprometer a segurança viária. Acioná-lo em movimento, sem necessidade, é considerado infração e demonstra falta de domínio sobre o uso dos dispositivos do veículo.' WHERE codigo_val = 'VAL-CTB-251-I';
UPDATE exam_rules SET descricao = 'Durante o exame de direção, o candidato deve utilizar corretamente o sistema de iluminação do veículo, evitando o acionamento intermitente das luzes alta e baixa sem necessidade.
O uso incorreto dessas luzes pode causar ofuscamento, confusão e risco de sinistros, principalmente à noite ou em vias de mão dupla.
As luzes intermitentes devem ser utilizadas somente em situações específicas de advertência ou segurança, conforme previsto no CTB.' WHERE codigo_val = 'VAL-CTB-251-II';
UPDATE exam_rules SET descricao = 'Durante o exame de direção, o candidato deve manter ambos os braços dentro do veículo e posicionados corretamente para o controle da direção. Conduzir com o braço para fora da janela compromete a segurança, reduz a capacidade de reação em situações de risco e fere o princípio da direção defensiva. Além disso, essa atitude demonstra postura inadequada e falta de domínio sobre o veículo durante a condução.' WHERE codigo_val = 'VAL-CTB-252-I';
UPDATE exam_rules SET descricao = 'Durante o exame de direção, o candidato deve manter o posicionamento correto das mãos e braços no volante e o interior do veículo livre de objetos, pessoas ou animais que possam interferir na condução. Transportar pessoas, animais ou volumes à esquerda ou entre os braços e pernas compromete o controle do veículo e a segurança da direção, configurando prática inadequada e infração média.' WHERE codigo_val = 'VAL-CTB-252-II';
UPDATE exam_rules SET descricao = 'Durante o exame de direção, o candidato deve utilizar calçado adequado, que se firme aos pés e permita total controle dos pedais (embreagem, freio e acelerador).
O uso de chinelos, sandálias frouxas, sapatos de salto alto ou calçados que se desprendam com facilidade põe em risco o controle do veículo e caracteriza infração média.
Essa conduta demonstra falta de atenção à segurança e à preparação para condução veicular.' WHERE codigo_val = 'VAL-CTB-252-IV';
UPDATE exam_rules SET descricao = 'Durante o exame de direção, o candidato deve manter ambas as mãos no volante, garantindo controle, estabilidade e segurança na condução. Dirigir com apenas uma das mãos, fora das exceções previstas (mudança de marcha, acionamento de equipamentos ou sinalização regulamentar), reduz a precisão e o tempo de resposta em situações de risco. Essa conduta demonstra postura inadequada e falta de atenção aos princípios de direção defensiva.' WHERE codigo_val = 'VAL-CTB-252-V';
UPDATE exam_rules SET descricao = 'Durante o exame de direção, o candidato não deve utilizar fones de ouvido, fones bluetooth ou aparelhos de telefonia celular enquanto conduz o veículo. Essa conduta reduz a percepção auditiva e a atenção ao ambiente, comprometendo a segurança do condutor e dos demais usuários da via. O uso de fones ou celulares durante a condução demonstra distração e desrespeito às normas de segurança, contrariando os princípios de direção defensiva.' WHERE codigo_val = 'VAL-CTB-252-VI';
